// action types

// TARGETS
export const LOAD_TARGETS_SUCCESS = 'LOAD_TARGETS_SUCCESS';
export const LOAD_TARGETS_FAILED = 'LOAD_TARGETS_FAILED';
export const ADD_TARGET_SUCCESS = 'ADD_TARGET_SUCCESS';
export const ADD_TARGET_FAILED = 'ADD_TARGET_FAILED';

// TOPICS
export const LOAD_TOPICS_SUCCESS = 'LOAD_TOPICS_SUCCESS';
export const LOAD_TOPICS_FAILED = 'LOAD_TOPICS_FAILED';
